project:
  type: book

book:
  title: "LING200 0101 SPRING 2025"
  author: "Utku Turk"
  description: "PS helper book and handouts"
  date: today
  date-format: long
  # cover-image: assets/media/cover.png
  site-url: https://utkuturk.com/ling200
  repo-url: https://github.com/utkuturk/ling200
  repo-actions: [edit, issue]
  reader-mode: true
  # downloads: [pdf]
  page-footer:
    border: true
    left: |
      <a href="https://umd.instructure.com/">ELMS</a> | <a href="https://piazza.com/class/m6fjfrepp2d458">Piazza</a>
    center: |
      Handsout of <a href='https://utkuturk.com'>utku turk</a>
    right: |
      Email me any of your questions utkuturk @ umd . edu.

  sidebar:
    search: true
    # logo: assets/media/plume.png
  chapters:
    - index.qmd
    - sections/intro.qmd
    # # - part: Below Word
    # #   chapters:
    # #     - sections/below/phonetics.qmd
    # #     - sections/below/phonology.qmd
    # #     - sections/below/morphology.qmd
    # # - part: Above Word
    # #   chapters:
    # #     - sections/above/syntax.qmd
    # #     - sections/above/bees.qmd
    # #     - sections/above/variation.qmd
    # - sections/references.qmd
    # - sections/misc.qmd

bibliography: assets/bib/references.bib

format:
  html:
    theme:
      light: lumen
      dark: darkly
    highlight-style: a11y
    fig-align: center
    code-link: true
    code-copy: true
    link-external-newwindow: true
    citation-location: margin
    css:
      - assets/helpers/custom.css
      - assets/helpers/custom.scss
    lightbox: true
    html-table-processing: none
    mainfont: "Nunito Sans"
    monofont: "JetBrains Mono"
  # pdf:
  #   include-in-header: "assets/helpers/preamble.tex"
  #   keep-tex: true
